#!/bin/sh
# Daniel Kim (otter.pro): load vim after cd into dropbox/notes
case "$OSTYPE" in
	darwin*) 
		#note_path=~/Dropbox/_notes
		note_path=/Volumes/Samsung128/Dropbox/_notes
		editor=mvim
		;;
	*) 
		note_path=~/_notes
		editor=vim
		;;
esac
	cd $note_path
	$editor +CtrlP
